// Generates src/app/theme.css: Tailwind colour families as CSS variables, with a dark
// variant that flips each scale (50 <-> 950, 100 <-> 900, ...). Run: node scripts/gen-theme.js
const fs = require("fs");
const colors = require("tailwindcss/colors");
const FAMILIES = ["green", "red", "amber", "sky", "violet", "teal"];
const SHADES = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"];
const rgb = (hex) => { const n = parseInt(hex.slice(1), 16); return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`; };
const mirror = (s) => SHADES[SHADES.length - 1 - SHADES.indexOf(s)];
// Hand-tuned dark greys with the app's slight teal tint (light greys = Tailwind slate).
const slateDark = { 50: "#17232a", 100: "#1c2a31", 200: "#2a3a42", 300: "#3a4b52", 400: "#5c6e75", 500: "#7f9197", 600: "#a2b2b7", 700: "#c3cfd3", 800: "#dde6e8", 900: "#eef3f4", 950: "#f8fafb" };

let light = "", dark = "";
for (const s of SHADES) { light += `  --slate-${s}: ${rgb(colors.slate[s])};\n`; dark += `  --slate-${s}: ${rgb(slateDark[s])};\n`; }
for (const f of FAMILIES) for (const s of SHADES) { light += `  --${f}-${s}: ${rgb(colors[f][s])};\n`; dark += `  --${f}-${s}: ${rgb(colors[f][mirror(s)])};\n`; }

const css = `/* GENERATED by scripts/gen-theme.js — do not edit by hand. */
:root {
  --bg: 246 247 249;
  --fg: 15 23 42;
  --surface: 255 255 255;
  --ink: 15 23 42;
  --ink-fg: 255 255 255;
${light}}
html.dark {
  color-scheme: dark;
  --bg: 11 18 21;
  --fg: 226 234 236;
  --surface: 18 28 33;
  --ink: 226 234 236;
  --ink-fg: 11 18 21;
${dark}}
`;
fs.writeFileSync("src/app/theme.css", css);
console.log("theme.css written:", css.split("\n").length, "lines");
